dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - cd curiosidade-domiciliar

install:
  - npm install

jobs:
  include:
    - stage: test
      script: npm run lint
      script: npm run test-headless`
    - stage: build
      script: npm run build:prod
      script: docker build -t curiosidade-domiciliar .
    - stage: acceptance
      script: docker run -d -p 80:80 --name curiosidade-domiciliar curiosidade-domiciliar
      script: npm run e2e:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)