dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - nginx

cache:
  directories:
     - ./node_modules

before_install:
  - cd curiosidade-domiciliar

install:
  - npm install

script:
  - npm run lint
  - npm run test-headless
  - npm run build:prod
  - nginx -c /home/travis/build/gradzio/home-curiosity/curiosidade-domiciliar/nginx/ci.conf
  - npm run e2e:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)