dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - cd curiosidade-domiciliar

install:
  - npm install

stages:
  - test
  - build
  - acceptance

jobs:
  include:
    # - stage: test
    #   script:
    #     - npm run lint
    #     - npm run test-headless
    #     - bash <(curl -s https://codecov.io/bash)
    - stage: build
      script:
        - npm run build:prod
        - docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA
    - stage: acceptance
      script:
        - docker pull $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA
        - docker run -d -p 80:80 $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA
        - npm run e2e:ci