dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./curiosidade-domiciliar/node_modules

before_install:
  - cd curiosidade-domiciliar

stages:
  - test
  - build
  - acceptance

jobs:
  include:
    - stage: test
      install: npm install
      script:
        - npm run lint
        - npm run test-headless
        - bash <(curl -s https://codecov.io/bash)
    - stage: build
      install: npm install --production
      script:
        - npm run build:prod
        - docker build -t $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA
    - stage: acceptance
      install: npm install -g cypress
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA
        - docker run -d -p 80:80 $DOCKER_USERNAME/$DOCKER_REPO:$TRAVIS_PULL_REQUEST_SHA
        - cypress run --record --key $CYPRESS_KEY --env host=localhost