dist: trusty
sudo: false

language: node_js
node_js:
  - "8"
  
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
     - ./node_modules

before_install:
  - cd curiosidade-domiciliar

install:
  - npm install

script:
  - npm run lint
  - npm run test-headless
  - npm run build:prod
  - docker build -t curiosidade-domiciliar .
  - docker run -p 80:80 --name curiosidade-domiciliar curiosidade-domiciliar
  - npm run e2e:ci

after_success:
  - bash <(curl -s https://codecov.io/bash)