apiVersion: v1
kind: Service
metadata:
  name: cur-dom
  labels:
    app: cur-dom
spec:
  ports:
    - port: 80
  selector:
    app: cur-dom
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: cur-dom
  labels:
    app: cur-dom
spec:
  selector:
    matchLabels:
      app: cur-dom
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cur-dom
        tier: frontend
    spec:
      containers:
      - image: ortho23/curiosidade-domiciliar:staging
        name: cur-dom
        ports:
        - containerPort: 80
          name: cur-dom
      imagePullSecrets:
      - name: docker-auth